<?php
/**
 * @file
 * This module enables a webform setting to anonymize the webform's results from everyone.
 *
 * @author Daniel Imhoff
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function webform_anonymous_form_webform_configure_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'webform_anonymous_form_webform_configure_form_submit';

  $form['submission']['anonymous'] = array(
    '#type' => 'radios',
    '#title' => t('Anonymize results'),
    '#description' => t('Make the results of this webform anonymous to everyone.'),
    '#options' => array(
      1 => t('Yes'),
      0 => t('No'),
    ),
    '#default_value' => _webform_anonymous_fetch_anonymous_status($form['#node']->nid) ? 1 : 0,
  );
}

/**
 * Additional submit handler for saving whether or not the webform results are anonymous.
 */
function webform_anonymous_form_webform_configure_form_submit(&$form, &$form_state) {
  // Fetch the preexisting value.
  $existing = _webform_anonymous_fetch_anonymous_status($form_state['values']['nid']);

  // No need to do all this work if it wasn't changed.
  if ($form_state['values']['anonymous'] !== $existing) {
    $record = array(
      'nid' => $form_state['values']['nid'],
      'anonymous' => $form_state['values']['anonymous'],
    );

    // Insert or update the anonymous status of this webform.
    drupal_write_record('webform_anonymous', $record, FALSE === $existing ? array() : 'nid');

    // If the results of webform should be made anonymous...
    if ($form_state['values']['anonymous']) {
      // Grab preexisting submission information from the {webform_submissions} table.
      $results = db_select('webform_submissions', 'w', array('fetch' => PDO::FETCH_ASSOC))
        ->condition('w.nid', $form_state['values']['nid'])
        ->fields('w')
        ->execute()
        ->fetchAllAssoc('sid');

      // Delete previous submissions.
      db_delete('webform_anonymous_submissions')
        ->condition('nid', $form_state['values']['nid'])
        ->execute();

      // Save the preexisting submission information in a separate table.
      $query = db_insert('webform_anonymous_submissions')
        ->fields(array('sid', 'nid', 'uid'));

      foreach ($results as $sid => $result) {
        $query->values(array(
          'sid' => $sid,
          'nid' => $result['nid'],
          'uid' => $result['uid'],
        ));
      }

      $query->execute();

      // Anonymize the submissions in the {webform_submissions} table.
      db_update('webform_submissions')
        ->fields(array(
          'uid' => 0,
        ))
        ->condition('nid', $form_state['values']['nid'])
        ->execute();
    }
    // Else, we need to bring back all that information.
    else {
      $results = db_select('webform_anonymous_submissions', 'w', array('fetch' => PDO::FETCH_ASSOC))
        ->condition('w.nid', $form_state['values']['nid'])
        ->fields('w')
        ->execute()
        ->fetchAllAssoc('sid');

      // Replace each uid value to what it was originally.
      foreach ($results as $sid => $result) {
        drupal_write_record('webform_submissions', $result, 'sid');
      }

      // Drop unneeded data.
      db_delete('webform_anonymous_submissions')
        ->condition('nid', $form_state['values']['nid'])
        ->execute();
    }
  }
}

/**
 * Grabs the anonymous setting of a webform based on the node ID that it belongs.
 *
 * @param $nid
 *   The node ID that the webform belongs.
 */
function _webform_anonymous_fetch_anonymous_status($nid) {
  return db_select('webform_anonymous', 'w', array('fetch' => PDO::FETCH_ASSOC))
    ->condition('w.nid', $nid)
    ->fields('w')
    ->execute()
    ->fetchField(1);
}
